spring:
  #spring boot admin的登陆账号和密码配置
  security:
    user:
      name: admin
      password: 123456
  mail:
    host: smtp.qq.com
    port: 465
    username: xxxx@qq.com
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  boot:
    admin:
      notify:
        mail:
          from: xx@qq.com
          to: xx@163.com

  #通过rabbit MQ将日志发给zipkin

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  config: classpath:logback-spring.xml

app:
  id: monitor                           #应用ID
apollo:
  meta: http://192.168.31.166:8080            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前


