app:
  id: auth                           #应用ID
apollo:
  meta: http://192.168.31.166:8080            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.31.187:3306/sc_auth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      jwt:
        signingKey: test-cloud